// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSAc9lGZRyxrkrWlJkasBSAtuZgTRK1gQ',
    appId: '1:823167941591:web:cc02caf31c6094c6c62992',
    messagingSenderId: '823167941591',
    projectId: 'hogarfix-81c90',
    authDomain: 'hogarfix-81c90.firebaseapp.com',
    storageBucket: 'hogarfix-81c90.firebasestorage.app',
    measurementId: 'G-YBVKZSZ5YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ5ZZXmHJt4kzfdOiNpdDqXYfm55w3c8s',
    appId: '1:823167941591:android:a0cdb7fa89d5c9a0c62992',
    messagingSenderId: '823167941591',
    projectId: 'hogarfix-81c90',
    storageBucket: 'hogarfix-81c90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3mCMMm5DvDGkt8i7yn9EpkEmx9LVMbAo',
    appId: '1:823167941591:ios:b4c991937c33bbb1c62992',
    messagingSenderId: '823167941591',
    projectId: 'hogarfix-81c90',
    storageBucket: 'hogarfix-81c90.firebasestorage.app',
    iosBundleId: 'com.example.hogarfixapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3mCMMm5DvDGkt8i7yn9EpkEmx9LVMbAo',
    appId: '1:823167941591:ios:b4c991937c33bbb1c62992',
    messagingSenderId: '823167941591',
    projectId: 'hogarfix-81c90',
    storageBucket: 'hogarfix-81c90.firebasestorage.app',
    iosBundleId: 'com.example.hogarfixapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSAc9lGZRyxrkrWlJkasBSAtuZgTRK1gQ',
    appId: '1:823167941591:web:bb90885ae6ae0dc2c62992',
    messagingSenderId: '823167941591',
    projectId: 'hogarfix-81c90',
    authDomain: 'hogarfix-81c90.firebaseapp.com',
    storageBucket: 'hogarfix-81c90.firebasestorage.app',
    measurementId: 'G-F4Q4W16P6E',
  );
}
